version: '3.7'
services:
  tasker:
    build: .
    tty: true
    volumes:
      - ./:/usr/src/app/tasker
    working_dir: /usr/src/app/tasker
    ports:
      - "5005:5005"
    networks:
      - tasker_network
  tasker_dev:
    container_name: tasker_dev
    build: .
    tty: true
    volumes:
      - ./:/usr/src/app/tasker
    working_dir: /usr/src/app/tasker
    ports:
      - "3000:3000"
    command: bash -c "yarn && yarn dev"
    depends_on:
      - db
    networks:
      - tasker_network
  db:
    image: mysql:5.7
    container_name: tasker_dev_db
    restart: always
    volumes:
      - tasker_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasker_dev
      MYSQL_USER: tasker
      MYSQL_PASSWORD: tasker
    ports:
      - "3330:3330"
    networks:
      - tasker_network
volumes:
  tasker_db:
networks:
  tasker_network:
